#Porta onde a aplicação será executada
server:
  port: 8082

spring:
  application:
    name: fastfood-production-service
  rabbitmq:
    host: ${RABBIT_HOST:rabbitmq}
    port: 5672
    username: ${RABBIT_USERNAME:guest}
    password: ${RABBIT_PASSWORD:guest}

    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          multiplier: 2
          max-interval: 300000

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:root}
      database: ${MONGO_DB:db_pedidos_producao}
      port: 27017
      authentication-database: admin

