apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fastfood-production-mongo-statefulset
  labels:
    app: fastfood-production-mongo
spec:
  replicas: 1
  template:
    metadata:
      name: fastfood-production-mongo
      labels:
        app: fastfood-production-mongo
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: fastfood-production-mongo-container
          image: mongo:4.0.3
          args: ["--dbpath", "data/db"]
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastfood-production-mongo-secret-opaque
                  key: MONGO_INITDB_ROOT_USERNAME

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-production-mongo-secret-opaque
                  key: MONGO_INITDB_ROOT_PASSWORD

            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: fastfood-production-mongo-secret-opaque
                  key: MONGO_INITDB_DATABASE

  selector:
    matchLabels:
      app: fastfood-production-mongo
  serviceName: fastfood-production-mongo-service
