apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastfood-production-deployment
  labels:
    app: fastfood-production
spec:
  replicas: 1
  template:
    metadata:
      name: fastfood-production
      labels:
        app: fastfood-production
    spec:
      containers:
        - name: fastfood-production-container
          image: soatpostech/fastfood-production:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: fastfood-production-secret-opaque
                  key: MONGO_HOST

            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastfood-production-secret-opaque
                  key: MONGO_USERNAME

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-production-secret-opaque
                  key: MONGO_PASSWORD

            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: fastfood-production-secret-opaque
                  key: MONGO_DB
            
            - name: RABBIT_HOST
              valueFrom:
                secretKeyRef:
                  name: fastfood-production-secret-opaque
                  key: RABBIT_HOST

            - name: RABBIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: fastfood-production-secret-opaque
                  key: RABBIT_USERNAME

            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fastfood-production-secret-opaque
                  key: RABBIT_PASSWORD
#          livenessProbe:
#            httpGet:
#              path: /actuator/health/
#              port: 8080
#            periodSeconds: 10
#            failureThreshold: 3
#            initialDelaySeconds: 30
#          readinessProbe:
#             httpGet:
#               path: /actuator/health
#               port: 8080
#             periodSeconds: 10
#             failureThreshold: 5
#             initialDelaySeconds: 10
#          resources:
#            requests:
#              cpu: 10m
  selector:
    matchLabels:
      app: fastfood-production
