apiVersion: v1
kind: Secret
metadata:
  name: fastfood-production-secret-opaque
type: Opaque
stringData:
  MONGO_HOST: fastfood-production-mongo-service
  MONGO_USERNAME: product-production
  MONGO_PASSWORD: product-production-123
  MONGO_DB: db_pedidos_producao
  RABBIT_HOST: fastfood-production-rabbit-service
  RABBIT_USERNAME: product-production
  RABBIT_PASSWORD: product-production-123
